services:
  kafka:
    image: apache/kafka:4.1.1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    healthcheck:
      test:
        [
          "CMD",
          "/opt/kafka/bin/kafka-broker-api-versions.sh",
          "--bootstrap-server",
          "kafka:9092",
        ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - crypto-dashboard
    restart: always

  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./table.sql:/docker-entrypoint-initdb.d/table.sql:z
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - crypto-dashboard
    restart: always

  kafka-init:
    image: apache/kafka:4.1.1
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command:
      - /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --topic btc_usd --if-not-exists
    networks:
      - crypto-dashboard

  listener:
    build:
      context: .
      dockerfile: Dockerfile
      target: listener
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    environment:
      KAFKA_HOST: kafka:9092
      COINBASE_WS: wss://ws-feed.exchange.coinbase.com
    restart: unless-stopped
    networks:
      - crypto-dashboard

  persistence:
    build:
      context: .
      dockerfile: Dockerfile
      target: persistence
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      listener:
        condition: service_started
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      KAFKA_HOST: kafka:9092
    restart: unless-stopped
    networks:
      - crypto-dashboard
