apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-init
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kafka-init
          image: apache/kafka:4.1.1
          command:
            - sh
            - -c
            - |
              /opt/kafka/bin/kafka-topics.sh \
                --bootstrap-server kafka:9092 \
                --create \
                --if-not-exists \
                --topic btc_usd
